delete from country;
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AO', '安哥拉', 'Angola', '0244', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AF', '阿富汗', 'Afghanistan', '93', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AL', '阿尔巴尼亚', 'Albania', '335', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('DZ', '阿尔及利亚', 'Algeria', '213', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AD', '安道尔共和国', 'Andorra', '376', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AI', '安圭拉岛', 'Anguilla', '1254', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AG', '安提瓜和巴布达', 'Antigua and Barbuda', '1268', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AR', '阿根廷', 'Argentina', '54', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AM', '亚美尼亚', 'Armenia', '374', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '阿森松', 'Ascension', '247', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AU', '澳大利亚', 'Australia', '61', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AT', '奥地利', 'Austria', '43', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AZ', '阿塞拜疆', 'Azerbaijan', '994', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BS', '巴哈马', 'Bahamas', '1242', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BH', '巴林', 'Bahrain', '973', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BD', '孟加拉国', 'Bangladesh', '880', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BB', '巴巴多斯', 'Barbados', '1246', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BY', '白俄罗斯', 'Belarus', '375', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BE', '比利时', 'Belgium', '32', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BZ', '伯利兹', 'Belize', '501', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BJ', '贝宁', 'Benin', '229', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '百慕大群岛', 'Bermuda Is', '1441', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BO', '玻利维亚', 'Bolivia', '591', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BW', '博茨瓦纳', 'Botswana', '267', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BR', '巴西', 'Brazil', '55', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BN', '文莱', 'Brunei', '673', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BG', '保加利亚', 'Bulgaria', '359', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BF', '布基纳法索', 'Burkina Faso', '226', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MM', '缅甸', 'Burma', '95', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('BI', '布隆迪', 'Burundi', '257', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CM', '喀麦隆', 'Cameroon', '237', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CA', '加拿大', 'Canada', '1', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KY', '开曼群岛', 'Cayman Is', '1345', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CF', '中非共和国', 'Central African Republic', '236', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TD', '乍得', 'Chad', '235', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CL', '智利', 'Chile', '56', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CN', '中国', 'China', '86', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CO', '哥伦比亚', 'Colombia', '57', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '刚果', 'Congo', '242', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CK', '库克群岛', 'Cook Is', '682', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CR', '哥斯达黎加', 'Costa Rica', '506', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CU', '古巴', 'Cuba', '53', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CY', '塞浦路斯', 'Cyprus', '357', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CZ', '捷克', 'Czech Republic', '420', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('DK', '丹麦', 'Denmark', '45', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('DJ', '吉布提', 'Djibouti', '253', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '多米尼加共和国', 'Dominica Rep', '1890', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('EC', '厄瓜多尔', 'Ecuador', '593', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('EG', '埃及', 'Egypt', '20', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SV', '萨尔瓦多', 'EI Salvador', '503', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('EE', '爱沙尼亚', 'Estonia', '372', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ET', '埃塞俄比亚', 'Ethiopia', '251', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('FJ', '斐济', 'Fiji', '679', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('FI', '芬兰', 'Finland', '358', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('FR', '法国', 'France', '33', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GF', '法属圭亚那', 'French Guiana', '594', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '法属玻利尼西亚', 'French Polynesia', '689', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GA', '加蓬', 'Gabon', '241', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GM', '冈比亚', 'Gambia', '220', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GE', '格鲁吉亚', 'Georgia', '995', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('DE', '德国', 'Germany', '49', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GH', '加纳', 'Ghana', '233', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GI', '直布罗陀', 'Gibraltar', '350', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GR', '希腊', 'Greece', '30', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GD', '格林纳达', 'Grenada', '1809', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GU', '关岛', 'Guam', '1671', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GT', '危地马拉', 'Guatemala', '502', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GN', '几内亚', 'Guinea', '224', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GY', '圭亚那', 'Guyana', '592', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('HT', '海地', 'Haiti', '509', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('HN', '洪都拉斯', 'Honduras', '504', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('HK', '香港', 'Hongkong', '852', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('HU', '匈牙利', 'Hungary', '36', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IS', '冰岛', 'Iceland', '354', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IN', '印度', 'India', '91', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ID', '印度尼西亚', 'Indonesia', '62', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IR', '伊朗', 'Iran', '98', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IQ', '伊拉克', 'Iraq', '964', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IE', '爱尔兰', 'Ireland', '353', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IL', '以色列', 'Israel', '972', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('IT', '意大利', 'Italy', '39', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CI', '科特迪瓦', 'Ivory Coast', '225', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('JM', '牙买加', 'Jamaica', '1876', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('JP', '日本', 'Japan', '81', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('JO', '约旦', 'Jordan', '962', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KH', '柬埔寨', 'Kampuchea (Cambodia )', '855', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KZ', '哈萨克斯坦', 'Kazakstan', '327', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KE', '肯尼亚', 'Kenya', '254', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KR', '韩国', 'Korea', '82', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KW', '科威特', 'Kuwait', '965', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KG', '吉尔吉斯坦', 'Kyrgyzstan', '331', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LA', '老挝', 'Laos', '856', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LV', '拉脱维亚', 'Latvia', '371', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LB', '黎巴嫩', 'Lebanon', '961', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LS', '莱索托', 'Lesotho', '266', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LR', '利比里亚', 'Liberia', '231', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LY', '利比亚', 'Libya', '218', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LI', '列支敦士登', 'Liechtenstein', '', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LT', '立陶宛', 'Lithuania', '370', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LU', '卢森堡', 'Luxembourg', '352', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MO', '澳门', 'Macao', '853', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MG', '马达加斯加', 'Madagascar', '261', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MW', '马拉维', 'Malawi', '265', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MY', '马来西亚', 'Malaysia', '60', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MV', '马尔代夫', 'Maldives', '960', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ML', '马里', 'Mali', '223', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MT', '马耳他', 'Malta', '356', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '马里亚那群岛', 'Mariana Is', '1670', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MQ', '马提尼克', 'Martinique', '596', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MU', '毛里求斯', 'Mauritius', '230', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MX', '墨西哥', 'Mexico', '52', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MD', '摩尔多瓦', 'Moldova', '373', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MC', '摩纳哥', 'Monaco', '377', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MN', '蒙古', 'Mongolia', '976', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '蒙特塞拉特岛', 'Montserrat Is', '1664', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MA', '摩洛哥', 'Morocco', '212', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('MZ', '莫桑比克', 'Mozambique', '258', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NA', '纳米比亚', 'Namibia', '264', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NR', '瑙鲁', 'Nauru', '674', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NP', '尼泊尔', 'Nepal', '977', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '荷属安的列斯', 'Netheriands Antilles', '599', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NL', '荷兰', 'Netherlands', '31', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NZ', '新西兰', 'New Zealand', '64', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NI', '尼加拉瓜', 'Nicaragua', '505', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NE', '尼日尔', 'Niger', '227', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NG', '尼日利亚', 'Nigeria', '234', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('KP', '朝鲜', 'North Korea', '850', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('NO', '挪威', 'Norway', '47', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('OM', '阿曼', 'Oman', '968', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PK', '巴基斯坦', 'Pakistan', '92', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PA', '巴拿马', 'Panama', '507', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PG', '巴布亚新几内亚', 'Papua New Cuinea', '675', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PY', '巴拉圭', 'Paraguay', '595', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PE', '秘鲁', 'Peru', '51', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PH', '菲律宾', 'Philippines', '63', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PL', '波兰', 'Poland', '48', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PT', '葡萄牙', 'Portugal', '351', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('PR', '波多黎各', 'Puerto Rico', '1787', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('QA', '卡塔尔', 'Qatar', '974', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '留尼旺', 'Reunion', '262', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('RO', '罗马尼亚', 'Romania', '40', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('RU', '俄罗斯', 'Russia', '7', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LC', '圣卢西亚', 'Saint Lueia', '1758', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '圣文森特岛', 'Saint Vincent', '1784', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '东萨摩亚(美)', 'Samoa Eastern', '684', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '西萨摩亚', 'Samoa Western', '685', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SM', '圣马力诺', 'San Marino', '378', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ST', '圣多美和普林西比', 'Sao Tome and Principe', '239', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SA', '沙特阿拉伯', 'Saudi Arabia', '966', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SN', '塞内加尔', 'Senegal', '221', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SC', '塞舌尔', 'Seychelles', '248', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SL', '塞拉利昂', 'Sierra Leone', '232', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SG', '新加坡', 'Singapore', '65', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SK', '斯洛伐克', 'Slovakia', '421', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SI', '斯洛文尼亚', 'Slovenia', '386', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SB', '所罗门群岛', 'Solomon Is', '677', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SO', '索马里', 'Somali', '252', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ZA', '南非', 'South Africa', '27', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ES', '西班牙', 'Spain', '34', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LK', '斯里兰卡', 'SriLanka', '94', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('LC', '圣卢西亚', 'St.Lucia', '1758', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '圣文森特', 'St.Vincent', '1784', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SD', '苏丹', 'Sudan', '249', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SR', '苏里南', 'Suriname', '597', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SZ', '斯威士兰', 'Swaziland', '268', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SE', '瑞典', 'Sweden', '46', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('CH', '瑞士', 'Switzerland', '41', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('SY', '叙利亚', 'Syria', '963', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TW', '台湾省', 'Taiwan', '886', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TJ', '塔吉克斯坦', 'Tajikstan', '992', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TZ', '坦桑尼亚', 'Tanzania', '255', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TH', '泰国', 'Thailand', '66', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TG', '多哥', 'Togo', '228', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TO', '汤加', 'Tonga', '676', '大洋洲', 'OA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TT', '特立尼达和多巴哥', 'Trinidad and Tobago', '1809', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TN', '突尼斯', 'Tunisia', '216', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TR', '土耳其', 'Turkey', '90', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('TM', '土库曼斯坦', 'Turkmenistan', '993', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('UG', '乌干达', 'Uganda', '256', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('UA', '乌克兰', 'Ukraine', '380', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('AE', '阿拉伯联合酋长国', 'United Arab Emirates', '971', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('GB', '英国', 'United Kiongdom', '44', '欧洲', 'EU');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('US', '美国', 'United States of America', '1', '北美洲', 'NA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('UY', '乌拉圭', 'Uruguay', '598', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('UZ', '乌兹别克斯坦', 'Uzbekistan', '233', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('VE', '委内瑞拉', 'Venezuela', '58', '南美洲', 'SA');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('VN', '越南', 'Vietnam', '84', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('YE', '也门', 'Yemen', '967', '亚洲', 'AS');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '南斯拉夫', 'Yugoslavia', '381', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ZW', '津巴布韦', 'Zimbabwe', '263', '非洲', 'AF');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('undefined', '扎伊尔', 'Zaire', '243', '', '');
insert into country (code, cname, ename, phone_coe, continent, continent_jc) values ('ZM', '赞比亚', 'Zambia', '260', '非洲', 'AF');
